General:
  device: mps
  k-nearest: 10

Paths:
  embeddings_path: jinaai/jina-embeddings-v2-base-en
  llama_cpp_path: models/Meta-Llama-3-8B-Instruct-Q5_K_M.gguf
  websites_root: ./data/www.uni.lu/

Env_Variables:
  omp_num_threads: 1
  tokenizers_parallelism: false


